---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/gallery
  label: Image Gallery
  create: all
  match: "**/*"
  templates:
  - image-upload
- type: directory
  path: content/collection
  label: Collection
  create: all
  match: "**/*"
  templates:
  - product-page
upload_dir: src/assets/images
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename::year::month::day:"
build:
  preview_output_directory: "/"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
