---
label: Product Page
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: subtitle
  type: text
  config:
    required: false
  label: Subtitle
- name: available
  type: field_group
  config: {}
  fields:
  - name: is_available
    type: boolean
    label: Is Available
  - name: price
    type: text
    config:
      required: false
    label: Price
    showOnly:
      field: is_available
      value: true
  - name: product_id
    type: text
    config:
      required: false
    label: Product Id
  label: Available
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
- name: featured_image
  type: file
  config:
    maxSize: 64
  label: Featured Image
  description: 600 x 600px
- name: gallery
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: image-gallery
      file: 
      path: 
  label: Gallery
- name: product_specs
  type: field_group_list
  fields:
  - name: heading
    type: text
    config:
      required: false
    label: heading
  - name: spec_content
    type: blocks
    label: Spec Content
    template_types:
    - product-spec-single
    - product-spec-multi
    config:
      min: 
      max: 
  config:
    min: 
    max: 
    labelField: 
  label: Product Specs
- name: meta_data
  type: field_group
  config: {}
  fields:
  - name: meta_data_field
    type: include
    config: {}
    template: meta-data
    label: Meta Data Field
  label: Meta Data
pages:
- content/collection/strat-style.md
- content/collection/test-4.md
- content/collection/test.md
- content/collection/test3.md
