---
label: Product Page
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
- name: meta_data
  type: field_group
  config: {}
  fields:
  - name: meta_data_field
    type: include
    config: {}
    template: meta-data
    label: Meta Data Field
  label: Meta Data
pages:
- content/collection/strat-style.md
