---
label: Product Page
hide_body: true
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: subtitle
  type: text
  config:
    required: false
  label: Subtitle
- name: available
  type: field_group
  config: {}
  fields:
  - name: is_available
    type: boolean
    label: Is Available
  - name: price
    type: text
    config:
      required: false
    label: Price
    showOnly:
      field: is_available
      value: true
  label: Available
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
- name: meta_data
  type: field_group
  config: {}
  fields:
  - name: meta_data_field
    type: include
    config: {}
    template: meta-data
    label: Meta Data Field
  label: Meta Data
pages:
- content/collection/strat-style.md
- content/collection/test.md
