---
label: Product Spec Multi
hide_body: true
fields:
- name: row_heading
  type: text
  config:
    required: false
  label: Row Heading
- name: content
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Content
